language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - [[ "x$TRAVIS_PHP_VERSION" != "xhhvm" ]] && COVERAGE_FLAGS="--coverage --coverage-xml" # PHPUnit code coverage doesn't currently work under HHVM

install:
  - composer update --dev

script: vendor/bin/codecept run $COVERAGE_FLAGS
